### ISSUE TITLE
Fail to generate signed bundle/apk

### ISSUE THREAD

**Issue by Hokyjack** [TorryDo/Floating-Bubble-View#12]
Hi, this is a nice module.
I have only a problem that I'm not able to generate signed APP Bundle / APK.
Only the debug bundle / apk works.
It fails to find the definitions from the library. Is there anything i can do about it?
Thanks

**Comment by mvfuma** [comment]
Same here. Trace:

`3 issues were found when checking AAR metadata:

  1.  Dependency 'androidx.core:core:1.9.0' requires libraries and applications that
      depend on it to compile against version 33 or later of the
      Android APIs.

      :app is currently compiled against android-32.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 7.2.1 is 32.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 33, then update this project to use
      compileSdkVerion of at least 33.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).

  2.  Dependency 'androidx.core:core-ktx:1.9.0' requires libraries and applications that
      depend on it to compile against version 33 or later of the
      Android APIs.

      :app is currently compiled against android-32.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 7.2.1 is 32.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 33, then update this project to use
      compileSdkVerion of at least 33.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).

  3.  Dependency 'androidx.annotation:annotation-experimental:1.3.0' requires libraries and applications that
      depend on it to compile against version 33 or later of the
      Android APIs.

      :app is currently compiled against android-32.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 7.2.1 is 32.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 33, then update this project to use
      compileSdkVerion of at least 33.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).
`

**Comment by mvfuma** [comment]
When updating to compileSDK 33, my service no longer compiles

**Comment by TorryDo** [comment]
@mvfuma 
Thank you for your informations.
After update to compileSDK 33 and get rid of the error you posted above, you got this error right?

```
Duplicate class androidx.lifecycle.ViewModelLazy found in modules ...

Duplicate class androidx.lifecycle.ViewTreeViewModelKt found in modules lifecycle-viewmodel-2.5.1-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.1) ...

```

If so, please add two dependencies below to your module level build.gradle file:

```groovy
implementation "androidx.lifecycle:lifecycle-viewmodel:2.5.1"

implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"

```

The reason is a library called appcompat:2.5.1

Update later ...

**Comment by TorryDo** [comment]
Hi,

After some investigation, I've discovered that the issue was caused by some code that was removed/updated a long time ago. I have made the necessary changes to fix the issue, and it should now be resolved.

Feel free to re-open the issue if my response does not satisfy you or if you continue to experience any problems.

Thank you.
