### ISSUE TITLE
Bubble displays incorrectly in landscape mode

### ISSUE THREAD

**Issue by Honglixi99** [TorryDo/Floating-Bubble-View#32]
hello，When I am using the pad, the horizontal screen display, the bubble is not close to the screen

**Comment by TorryDo** [comment]
If I understand correctly, the problem you're facing is that the bubble is behaving incorrectly in landscape mode, is that correct?

**Comment by Honglixi99** [comment]
hello, yes, when i click this button while in portrait and then i rotate to landscape, the bubble doesn't get close to the edge of the screen

**Comment by TorryDo** [comment]
It's definitely a bug. I'm surprised I didn't notice it earlier! 😅

Thank you for bringing it to our attention!

**Comment by TorryDo** [comment]
hi @Honglixi99 , 👋

This bug has been fixed in `v0.5.3`. 
However, it still has some minor UI issues that I'll fix later.

Thank you.

**Comment by rajesht4101999** [comment]
can I lock it to portrait

**Comment by dofire** [comment]
@rajesht4101999 nope unfortunately, that's how android work

**Comment by rajesht4101999** [comment]
but when I change to landscape expanded bubble ui becomes half cut @TorryDo

**Comment by dofire** [comment]
@rajesht4101999 can you share a video about the issue you're facing?

**Comment by rajesht4101999** [comment]
https://drive.google.com/file/d/1IyBRsFoOcwu9I-C8F67DKSqwc779P_zu/view?usp=sharing

when I trigger to start bubble service in landscape mode
