### ISSUE TITLE
Close bubble icon & duplicate icon displayed

### ISSUE THREAD

**Issue by prabusharan** [TorryDo/Floating-Bubble-View#4]
Issues: 
1) Unable close service from the inside application without using the close button.
2) If the user calls the floating bubble service before closing the previous floating bubble means a new duplicate bubble will be created automatically.

![Screenshot_1669716180](https://user-images.githubusercontent.com/35057652/204500600-b63c9fa9-96f5-4b55-9013-9cd799813af0.png)

**Comment by TorryDo** [comment]
`Unable close service from the inside application without using the close button`

You can simply use the built-in function below to stop the bubble inside the app 
```kotlin
context.stopService(Intent(context, YourBubbleService::class.java))
``` 
`If the user calls the floating bubble service before closing the previous floating bubble means a new duplicate bubble will be created automatically`
Actually this is my intention from the beginning.
I've upgrade this library, please update to the latest version. After update, you can check if the bubble is already running
```kotlin
Boolean isBubbleRunning = FloatingBubbleService.isRunning()

if(isBubbleRunning){
   startService(...)
}else{
   stopService(...)
}
```

Thank you for your interest in this library.
