### ISSUE TITLE
Bubble resizing on click not working properly

### ISSUE THREAD

**Issue by Boguslawa-Tlolka** [TorryDo/Floating-Bubble-View#42]
### Steps to reproduce

1. Open sample app
2. Move bubble to the right side of the screen
3. Click next
4. If the bubble is changing it's size it's not working properly (part of it is outside the screen or it moves to the center and is not animated to the egde)

https://github.com/TorryDo/Floating-Bubble-View/assets/79993467/939173af-5bc5-4bc6-81bc-fb8ca71f7521

### Expected behavior

When bubble needs resizing after click it doesn't show outside the screen and if animate to edge is enabled it is dragged to the edge and not stays on the random place on the screen.

### Actual behavior

Part of bubble is outside the screen or it moves to the center and is not animated to the egde

### Floating-Bubble-View version

0.5.6

### Android version

I tried Android 13, Android 11 and Android Pie (9)

### Device

Pixel Emulator and Xiaomi Redmi Note 8 Pro (Android 11)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the library to the latest **[Version](https://github.com/torrydo/Floating-Bubble-View/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TorryDo** [comment]
Hi @Boguslawa-Tlolka, 👋

You can upgrade to the version `v0.6.x` and use `animateBubbleToEdge()`, this method will animate the bubble to the edge of the screen. 

If this response does not satisfy you, please don't hesitate to re-open the issue,
Thank you. 💖
