### ISSUE TITLE
Declaring MyClass in a separate file causes the bubble to not show up

### ISSUE THREAD

**Issue by z0xyz** [TorryDo/Floating-Bubble-View#46]
### Steps to reproduce

1. Declare the intent within the `MainActivity.kt` file.
2. Declare the `MyClasss` class within the same file.
3. After configuring the method of that class run
4. The bubble will show up
5. Modularize the code by getting `MyClass` in a separate file
6. Now the bubble doesn't show up

### Expected behavior

The bubble shows up whether `MyClass` is declared within the `MainActivity` file or another separate file.

### Actual behavior

The bubble shows up, only when `MyClass` is declared within the same file.

### Crash logs

No crash logs. It just doesn't show up silently.

### Floating-Bubble-View version

0.6.1

### Android version

10

### Device

Huwawei MRD-LX1F

### Other details

I'm using a physical device for testing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the library to the latest **[Version](https://github.com/torrydo/Floating-Bubble-View/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TorryDo** [comment]
Hi @z0xyz 👋,

I don't think the issue come from the library itself, you mentioned that the issue appear when you extract the service class to separated file, did you check the name of the service class in your manifest file?
```diff
...
     <service
+         android:name="<YOUR_PACKAGE>.MyService"
         android:foregroundServiceType="specialUse"
         >
         <property android:name="android.app.PROPERTY_SPECIAL_USE_FGS_SUBTYPE" android:value="foo"/>  <!-- optional -->
     </service>
...
```

Thank you 💖

**Comment by z0xyz** [comment]
Thanks. That resolved the problem. Thanks for your help.

**Comment by z0xyz** [comment]
I still have another issue that popped out
- Soft keyboard doesn't show up when selecting any text field at the expanded bubble.

I was also wondering if there was a convenient way / code snippet to incorporate Text selection event listener with chat bubbles. [REF](https://medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999)

**Comment by TorryDo** [comment]
> Soft keyboard doesn't show up when selecting any text field at the expanded bubble

Thank you for remind me, the next version will fix this issue

> you think this library would have a better/ more straightforward approach.

AFAIK, you can create an activity just for receive the highlighted text, and call `finish()` after ran the service [sample](https://gist.github.com/TorryDo/b19b9bfcaa8b0e72e87ee26afa2ec925)

**Comment by z0xyz** [comment]
>  v0.6.2 has fixed this issue
Great thanks!
> you can create an activity just for receiving the highlighted text, and call finish() after ran the service
I've tried to achieve that. In fact, I already did before on an XML project, but now that I'm using compose creating an activity class extending `ComponentActivity` just gives me an overlay of a white background.

**Comment by z0xyz** [comment]
Unlike the previous version, the latest one `0.6.2` automatically fills the entire screen, making items behind the floating bubble non-interactive, unless the bubble is closed.
I used to hack around it in the previous version by having a column that fills the entire screen, but unironically after I updated to the latest version, now I want the previous behavior.
I was wondering if this behavior could be toggled/opt-in feature.

**Comment by TorryDo** [comment]
Hi @z0xyz 👋,

Thanks for your suggestion, I'll support it if possible. 

You can do magic like this:
1. Create a column that fills the entire screen like you already did
2. Update `expandedBubble` layoutParams.flag before calling `expand()`
```diff
expandedBubble?.layoutParams?.flags = 
                    WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS or
+                    WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or
                    WindowManager.LayoutParams.FLAG_DIM_BEHIND
```
