### ISSUE TITLE
Close view is buggy

### ISSUE THREAD

**Issue by z0xyz** [TorryDo/Floating-Bubble-View#50]
## First - Scenario
1. Define an expanded bubble view
2. Just tap on the Icon
3. During the time at which the expanded view is opening, the bottom close icon remains visible

![image](https://github.com/TorryDo/Floating-Bubble-View/assets/48662854/73588f5d-9ff1-4407-ac03-1af2869bc599)

## Second Scenario
1. Drag the popup sideways for example
2. Drop the popup to be placed
3. The close button remains visible (sometimes)

![image](https://github.com/TorryDo/Floating-Bubble-View/assets/48662854/718ac60f-600c-41f0-9f43-79054c3b4a7e)

Maybe exposing [closeBubble](https://github.com/TorryDo/Floating-Bubble-View/blob/a1d16585d86ab5b9a5eaed43f2c3d03bbaf052f1/FloatingBubbleView/src/main/java/com/torrydo/floatingbubbleview/service/expandable/ExpandableBubbleService.kt#L133) might help, or even append it to the `minimize` call

### Expected behavior

The Bottom close icon should only be visible when the user is actively dragging the icon, then instantly close when not.

### Actual behavior

Outlined at the steps to reproduce

### Crash logs

N/A

### Floating-Bubble-View version

0.6.3

### Android version

Android 9.1

### Device

Huawei mrd-lx1

### Other details

The [project](https://github.com/z0xyz/knounce/tree/main/app/src/main/kotlin/com/polendina/knounce/presentation/shared/floatingbubble) that I've currently using.

https://github.com/TorryDo/Floating-Bubble-View/assets/48662854/bf363fe1-677b-4039-a126-9c8cbe3ca343

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the library to the latest **[Version](https://github.com/torrydo/Floating-Bubble-View/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TorryDo** [comment]
Hi @z0xyz 👋,
This bug has been fixed in [v0.6.4](https://github.com/TorryDo/Floating-Bubble-View/releases/tag/0.6.4). If you have any problems, don't hesitate to re-open the issue. Thank you. 💖

**Comment by z0xyz** [comment]
Thank you. I'll update the dependencies and test-run the new release.
