### ISSUE TITLE
Need to perform some action when view is expended.

### ISSUE THREAD

**Issue by nicemak** [TorryDo/Floating-Bubble-View#52]
### Describe your suggested feature

Thank you for the great library, i am developing an application which needs to perform some function without user action and set to textview, which is inside the layout `expandedView = LayoutInflater.from(this).inflate(R.layout.results, null)`. when expended view is visible this function will execute and perform some task. how to achieve this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the library to the latest **[Version](https://github.com/torrydo/Floating-Bubble-View/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nicemak** [comment]
@TorryDo

**Comment by TorryDo** [comment]
Hi @nicemak 👋. Sorry for the late reply,
If I understand your question correctly, you want to execute some functions after the expanded-view is visible and set the `TextView`  right? 

If so, then after you call `expand()` function to show the expanded-view, you can find the id of the TextView and set the text directly

```kotlin
val textView = expandedView.findViewById(R.id.yourTextViewId)
textView.text = "hello world"
```
