### ISSUE TITLE
Any way to apply custom image bitmap to the floating bubble?

### ISSUE THREAD

**Issue by akshaytandroid** [TorryDo/Floating-Bubble-View#53]
I see we have to use `val imgView = ViewHelper.fromDrawable(this, R.drawable.ic_rounded_blue_diamond, 60, 60)`

Is there a way, I can pass the bitmap from the activity to the CustomService.kt class so that I show the floating bubble with that passed image.

**Comment by TorryDo** [comment]
Hi @akshaytandroid 👋,

You can follow this [answer](https://stackoverflow.com/a/11010565/11004027) for passing Bitmap data. After you retrieved the Bitmap, you can use `val bm = ViewHelper.fromBitmap(...)`

If you have further concern, please let me know. Thank you. ❤️
