### ISSUE TITLE
Minimize bubble outise onCreate service

### ISSUE THREAD

**Issue by snigle** [TorryDo/Floating-Bubble-View#55]
### Steps to reproduce

```kotlin
 override fun onCreate() {
        super.onCreate()
        Timer().scheduleAtFixedRate(CustomTimerTask(this),0,5000)

    }


class CustomTimerTask(private val popup: Popup) : TimerTask() {
    override fun run() {
       // I want to do some check here and display the bubble if needed
        popup.minimize()
    }
}

```
### Expected behavior

The bubble is displayed by the timerTask

### Actual behavior

bubble is not displayed

### Floating-Bubble-View version

0.6.1

### Android version

API 33

### Device

Pixel 3a

### Other details

I also tried to start bubble service from a CoRoutine, it works but ifI declare a timer in my coroutine I have the same issue 

(I'm newbie in android development, maybe I miss something simple)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the library to the latest **[Version](https://github.com/torrydo/Floating-Bubble-View/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TorryDo** [comment]
Hi @snigle 👋,
You should call minimize() on the main thread and the issue will be solved, something like this 😊

p/s: You should upgrade the library to `v0.6.3`, thank you 💖

![image](https://github.com/TorryDo/Floating-Bubble-View/assets/85553681/8a756a66-8550-4dca-a00e-eb783ea570a6)

**Comment by snigle** [comment]
Thanks, I didn't know that! It works now :)
